name: kitchen_app
description: A quick meal preparation app that suggests recipes based on ingredients.

# Prevents publishing to pub.dev
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/2.png
